"""return back

Revision ID: 58336ecca3ec
Revises: bbe4467e852b
Create Date: 2023-09-06 23:41:37.721314

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '58336ecca3ec'
down_revision: Union[str, None] = 'bbe4467e852b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('hotels', 'visited')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hotels', sa.Column('visited', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
